server:
  port: 8888
  
spring:  datasource:    dynamic:
      primary: oracle #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后再为匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.      datasource:
        oracle: 
          url: jdbc:oracle:thin:@193.168.1.199:1521:test          driver-class-name: oracle.jdbc.driver.OracleDriver
          username: test          password: test                 mysql: 
          url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC          driver-class-name: com.mysql.cj.jdbc.Driver          username: root          password: 123456
mybatis-plus:  mapper-locations:  - classpath:mapper/*.xml